Fixed Icon Loader dll glitch in windows device
Sitois/Nuclear-V2 pull request #30
Opened 2024-12-13 05:16 UTC by GrimmDevcc

Added a workaround for iconloader dll in windows 10 and up.

2024-12-13 06:38 UTC, PROMPTYLOL commented
Looks nice. Good job.

2024-12-13 07:07 UTC, Sitois commented
It's 6 am for me bro wait

2024-12-13 07:44 UTC, PROMPTYLOL commented
bro please do this update. i need it badly

2024-12-13 09:52 UTC, Sitois commented
What is your PR about ?

2024-12-13 10:00 UTC, GrimmDevcc commented
Basically in newer windows python handles image differently so I fixed it by directly calling the image using a shell. This may cause false positives tho

2024-12-13 10:31 UTC, Lenochxd requested changes
I have identified several serious security and functionality concerns. As these changes introduce risks that could harm the project and its users, this pull request cannot be approved in its current state. Below is detailed feedback for each area of concern:

---

1. The binary file `nuclear_icon.png` has been modified. Its purpose and integrity are unclear. Running a `.png` file using `os.system` is dangerous. If this file is not a legitimate image, it will execute harmful actions.

2. **Dangerous Use of `os.system`**
The following code raises major red flags:
```python
os.system("nuclear_icon.png")
```
- Executing a file blindly in this way poses a significant security risk.

3. **Removal of Safeguards in `main.py`**
The original code included logic to safely handle files:
```python
with open('nuclear_icon.png', 'rb') as image:
    nuclear_icon = image.read()
```

This has been removed and replaced with unsafe execution using `os.system`. 

---

### Final Decision
This pull request introduces multiple serious security vulnerabilities and cannot be merged as is. Please address the feedback and resubmit if necessary. For now, this PR is rejected.

2024-12-15 04:54 UTC, PROMPTYLOL commented
I have checked the png and have determined it is a legitimate image.

2024-12-15 08:20 UTC, PROMPTYLOL commented
@Sitois

2025-01-22 08:23 UTC, Sitois commented
Gonna check that today

2025-01-22 18:08 UTC, PROMPTYLOL commented
This requires a update

2025-02-01 01:16 UTC, Sitois commented
It's just a stealer. Annoying. Reported.

2025-02-01 01:16 UTC, closed without merging

2025-02-01 01:20 UTC, Lenochxd commented
🤓